### ISSUE TITLE
Bug: map styling on "review" page

### ISSUE THREAD

**Issue by amenity** [cityofaustin/techstack#1283]
Blue box appears in place of close (X) and my location icons
 

**URL tested:** https://forms.austintexas.io/police-oversight/complaint/review-and-submit

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=71.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Freview-and-submit&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/review-and-submit) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 71.0 |
| Operating System | OS X Mojave |
| Resolution | 1548x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/c9c384968c22b264593f1666a589598e08e71943/macmo_chrome_71.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/c9c384968c22b264593f1666a589598e08e71943/macmo_chrome_71.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=71.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-oversight%2Fcomplaint%2Freview-and-submit&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-oversight/complaint/review-and-submit) to reproduce the issue on Browserstack**

**Comment by amenity** [comment]
Maybe relevant? https://github.com/cityofaustin/techstack/issues/1285#issuecomment-466705031

**Comment by amenity** [comment]
I'm actually seeing two boxes now. 😛 
<img width="878" alt="screen shot 2019-02-25 at 2 47 11 pm" src="https://user-images.githubusercontent.com/1463708/53367619-4914c700-390c-11e9-8669-505527db2352.png">

**Comment by sergiogcx** [comment]
Yes, thank you. Working on it as we speak.

**Comment by amenity** [comment]
@easherma I'm still seeing this 😕 
<img width="1541" alt="screen shot 2019-02-27 at 12 39 40 am" src="https://user-images.githubusercontent.com/1463708/53470780-414a4500-3a28-11e9-9d7f-58c91c95c43e.png">

**Comment by easherma** [comment]
@amenity I pushed to master but did not push to production :-/ unsure what our protocol is around this

**Comment by amenity** [comment]
<img width="811" alt="Screen Shot 2019-03-12 at 1 21 31 PM" src="https://user-images.githubusercontent.com/1463708/54225491-c96d2780-44c9-11e9-9922-44786729c6a5.png">
Still seeing at https://forms.austintexas.io/police-complain/review-and-submit. 🤔

**Comment by amenity** [comment]
@easherma FWIW, fiddling with these pesky guys in my inspector, it seems like setting the background color with RGBA like [Sergio did with the upload button](https://github.com/cityofaustin/techstack/issues/1285#issuecomment-467235955) is working better?

**Comment by easherma** [comment]
updating this as it's like my third time fixing. I might be able to hack something into play again, but really we need to refactor the review page and the way us-forms-system applies styles

**Comment by easherma** [comment]
this is tweaked to work/be visible again. but the review page is still doing goofy things to the styling so it looks ugly

**Comment by amenity** [comment]
Ugh, sorry this is such a pain. Looks like you squashed it for now, so I'll close this. Would you edit/elaborate on refactoring dreams [here](https://github.com/cityofaustin/techstack/issues/1463), please?
