### ISSUE TITLE
"Title" on review page

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#1507]
1. Fill out the form
2. Add officer or witness details
3. Go to review page
4. Open witness or officer accordions

Current behavior: A placeholder word "title" is mysteriously appearing at the top of officer and witness detail sections. 

- [ ] Change placeholder language for officers
- [ ] Change placeholder language for witnesses
- [ ] Add Spanish to translations.json

**URL tested:** https://forms.austintexas.io/police-complain/review-and-submit

Open [URL](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Freview-and-submit&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/review-and-submit) on Browserstack

|Property | Value|
|------------ | -------------|
| Browser | Chrome 72.0 |
| Operating System | OS X Mojave |
| Resolution | 1438x946 |

**Screenshot Attached** 
[Screenshot URL](https://live.browserstack.com/issue-tracker/f254ef29bd57447a26921296f9dcce6294f3a140/macmo_chrome_72.0.jpg)
 ![Screenshot URL](https://live.browserstack.com/issue-tracker/f254ef29bd57447a26921296f9dcce6294f3a140/macmo_chrome_72.0.jpg)

**[Click here](https://live.browserstack.com/dashboard#os=OS+X&os_version=Mojave&browser=Chrome&browser_version=72.0&zoom_to_fit=true&full_screen=true&url=https%3A%2F%2Fforms.austintexas.io%2Fpolice-complain%2Freview-and-submit&speed=1&start_element=ClickedReproduceIssueFromgithub&start=true&furl=https://forms.austintexas.io/police-complain/review-and-submit) to reproduce the issue on Browserstack**

**Comment by easherma** [comment]
fixed

**Comment by desigonz** [comment]
I'm still seeing this happen in staging: 
![image](https://user-images.githubusercontent.com/5839508/55027038-4cb27100-4fd2-11e9-92b9-720e8e3f83a9.png)
