### ISSUE TITLE
Remove "process page" from "create new content" modal

### ISSUE THREAD

**Issue by desigonz** [cityofaustin/techstack#2466]
We're replacing process pages with guides. Let's remove "process page" from the "create new content" modal.

![image](https://user-images.githubusercontent.com/5839508/60468739-32ff7600-9c20-11e9-88fc-775af0a53db8.png)

**Comment by easherma** [comment]
it would be nice to have these be generated dynamically

**Comment by desigonz** [comment]
@easherma that does sound nice! I'll create an issue for it and dev team can size it, but probably will backlog for now

**Comment by briaguya** [comment]
This may be more of a 3 but I figure with a 5 we'll have a better chance of catching everything (and maybe getting some bonus cleanup done that we didn't know we needed)

**Comment by desigonz** [comment]
@briaguya got rid of all instances of process pages in Janis. Need to do Joplin!

**Comment by desigonz** [comment]
Content team has backed up all of our content, so no need to migrate/preserve them.

**Comment by easherma** [comment]
Fixed by this I believe https://github.com/cityofaustin/joplin/pull/314

**Comment by desigonz** [comment]
@easherma Excellent! I still see them here: 
![image](https://user-images.githubusercontent.com/5839508/62582384-d7a15300-b871-11e9-8a01-9d52ea346fb7.png)

I can certainly delete any instances of them in Joplin, but are there technical debt issues we should be logging for y'all?

**Comment by briaguya** [comment]
@easherma I just removed it from the create content modal while adding guides to it.

The rest of the process page stuff is in models/__init__, so this still applies to doing a deeper clean of it
