### ISSUE TITLE
Special hours for related services on location pages not working in Spanish

### ISSUE THREAD

**Issue by ablangworthy27** [cityofaustin/techstack#4063]
## Describe the bug
I am working on adding translations to all the location pages I created a couple weeks ago, and the "special hours" box under the related service will not allow me to have two different languages.

When I add Spanish, it changes the English to Spanish as well. I try changing it back, but then the Spanish switches back to English as well. Ultimately I can only have it one way or the other.

## To Reproduce
Steps to reproduce the behavior 

1. Go to [location page](https://joplin.herokuapp.com/admin/pages/363/edit/#tab-content)
2. Scroll down to the related service called "Get help with rent and utility payments"
3. Toggle the language of the page to Spanish
4. In the text box for special hours, add a Spanish phrase
5. Toggle the language back to English. 
4. You will see that the language presented is Spanish and not English, as it should be. 

## Expected behavior
Typically, when I toggle the language to Spanish, input the Spanish text, and then toggle back to English, the English language text stays in English.

**Comment by chiaberry** [comment]
@ablangworthy27 & @desigonz 
here is a joplin to test on
https://joplin-pr-4063-special-horas.herokuapp.com/admin/pages/370/edit/#tab-content

I'll get a janis going so you can see whats happening / how it comes out

**Comment by chiaberry** [comment]
I'm using this janis: https://janis-3818-event-home.netlify.com/es/location/test-location-page, you can toggle languages and see the hours here

**Comment by ablangworthy27** [comment]
@chiaberry this looks good!

**Comment by desigonz** [comment]
QA passed!

**Comment by ablangworthy27** [comment]
@chiaberry @desigonz do I still need to wait before doing translations for special hours?

**Comment by desigonz** [comment]
@chiaberry it's not in production yet, right? Can you let Amanda know when it is?

**Comment by desigonz** [comment]
@ablangworthy27 This should be working. Closing this issue.

**Comment by ablangworthy27** [comment]
This is not fixed. You can look at [South Austin Neighborhood Center](https://alpha.austin.gov/es/location/south-austin-neighborhood-center) for an example. The special hours are not working for the location and they are not working for the service attached to the location. If you look on the Joplin side, you can see that there is Spanish and English copy, but it isn't working right on Janis

**Comment by chiaberry** [comment]
I'll take a look at it now Amanda, sorry its still not working

**Comment by desigonz** [comment]
It's working now! Closing this.
